bremersee:
  exception-mapping:
    api-paths:
      - /*/api/**
    default-exception-mapping-config:
      include-stack-trace: true
      include-cause: true
      include-application-name: true
      include-exception-class-name: true
      include-handler: true
      include-path: true

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"
  endpoint:
    health:
      show-details: always

server:
  port: ${SERVER_PORT:8080}

spring:
  sleuth:
    enabled: ${SLEUTH_ENABLED:false}
    sampler:
      probability: ${SLEUTH_PROBABILITY:1.0}
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

---

spring:
  profiles: basic-auth

bremersee:
  security:
    authentication:
      enable-jwt-support: false
      basic-auth-users:
        - name: "actuator"
          password: "actuator"
          authorities:
            - "ROLE_ACTUATOR"
        - name: "admin"
          password: "admin"
          authorities:
            - "ROLE_ACTUATOR_ADMIN"
      actuator:
        roles:
          - "ROLE_ACTUATOR"
        admin-roles:
          - "ROLE_ACTUATOR_ADMIN"

---

spring:
  profiles: swarm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: pts-route
#          uri: lb://pts
#          predicates:
#            - Path=/pts/**
#          filters:
#            - RewritePath=/pts/(?.*), /$\{path}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOST_NAME:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: ${server.port:80}

  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/"

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
