info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Bremersee's Spring Cloud Gateway.

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
        allowed-methods: "*"
        allowed-origins: "*"

server:
  port: ${SERVER_PORT:8080}

---

spring:
  profiles: swarm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: pts-route
#          uri: lb://pts
#          predicates:
#            - Path=/pts/**
#          filters:
#            - RewritePath=/pts/(?.*), /$\{path}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOST_NAME:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port: ${server.port:80}

  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/"

---

spring:
  profiles: dev
  cloud:
    inetutils:
      preferred-networks:
        - 10.0.7

---

spring:
  profiles: prod
  cloud:
    inetutils:
      preferred-networks:
        - 172.16.1
